import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {NextPage} from "next";
import Menu from "@/components/Menu";
import Banner from "@/components/Banner";
import LectureGroup from "@/components/lecture/LectureGroup";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu />
            <Banner />
            <LectureGroup />
            <div title="lectureList">
                <h1>강의목록</h1>
            </div>
            <footer className={styles.footer}>
                <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};
export default Home;
